[package]
name = "nnnoiseless"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
edition = "2018"

[[bin]]
name = "corr"
path = "src/corr.rs"

[dependencies]
num-complex = "0.2.4"
once_cell = "1.4.0"
rustfft = "3.0.1"

[dev-dependencies]
byteorder = "1.3.4"
