[package]
name = "rnnoise"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.71"
num-complex = "0.3.0"
once_cell = "1.4.0"
